import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { api } from "~/utils/api";
import Image from "next/image";
import { LoadingPage } from "~/components/loadingSpinner";
import type { ReactElement } from "react";
import Post from "~/components/post";
import { FeedSkeleton } from "~/components/skeletons";

dayjs.extend(relativeTime);

const NavBar = () => (
  <div className="flex h-fit w-full justify-end bg-red-200 p-4">
    <UserButton />
  </div>
);

const FeedWrapper = ({
  children,
}: {
  children: ReactElement[] | ReactElement;
}) => (
  <div className="flex h-screen justify-center">
    <div className="h-full w-full flex-col border-x-2 text-teal-300 md:w-2/3">
      <div className="h-48 flex-col items-center border-y-2">{children}</div>
    </div>
  </div>
);

const Feed = ({ image }: { image: string }) => {
  const { data, isLoading } = api.post.getPosts.useQuery();

  if (isLoading) return <FeedSkeleton />;

  if (!data) return <div>Something went wrong with the call</div>;

  return (
    <FeedWrapper>
      {data.map((post, i) => (
        <div key={i} className="flex h-48 items-center border-y-2">
          <Image
            src={image}
            width={48}
            height={48}
            alt="account pic"
            className="m-4 rounded-full "
          />
          <div className="flex flex-col">
            <div className="text-sm opacity-80">
              @{post.author} · {dayjs(post.createdAt.toISOString()).fromNow()}
            </div>
            <div className="text-xl">{post.content}</div>
          </div>
        </div>
      ))}
    </FeedWrapper>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>T3 Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-900">
        <NavBar />
        <Post />
        <Feed
          image={
            "https://media.istockphoto.com/id/1322220448/photo/abstract-digital-futuristic-eye.jpg?s=612x612&w=0&k=20&c=oAMmGJxyTTNW0XcttULhkp5IxfW9ZTaoVdVwI2KwK5s="
          }
        />
      </main>
    </>
  );
}
